package com.drmacze.f16launcher

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/**
 * DLavie Strings Catalog v3 — i18n untuk 10 bahasa.
 *
 * Usage:
 *   val lang = LanguageManager.getCurrentLanguage(context)
 *   val t = Strings.get(lang)
 *   Text(t.home)
 *
 * Atau via CompositionLocal:
 *   val t = LocalStrings.current
 *   Text(t.home)
 *
 * Languages: en, id, ms, pt, es, de, fr, ja, zh, ar
 */

data class DLavieStrings(
    // ─── Bottom nav labels ──────────────────────────────────────────────────
    val home: String,
    val discover: String,
    val dlc: String,
    val gameHub: String,
    val community: String,
    val profile: String,
    val update: String,

    // ─── Top bar ────────────────────────────────────────────────────────────
    val search: String,
    val searchPlaceholder: String,
    val notifications: String,
    val menu: String,

    // ─── Login screen ───────────────────────────────────────────────────────
    val loginTitle: String,
    val loginSubtitle: String,
    val loginWithGoogle: String,
    val loginWithEmail: String,
    val registerAccount: String,
    val continueAsGuest: String,
    val guestNotice: String,
    val login: String,
    val register: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val username: String,
    val displayName: String,
    val country: String,
    val forgotPassword: String,
    val back: String,
    val legalNotice: String,

    // ─── Profile setup dialog ───────────────────────────────────────────────
    val completeProfile: String,
    val completeProfileDesc: String,
    val saveAndContinue: String,

    // ─── Guest upgrade dialog ───────────────────────────────────────────────
    val loginRequired: String,
    val later: String,
    val loginNow: String,

    // ─── Hero carousel ──────────────────────────────────────────────────────
    val officialTag: String,
    val communityTag: String,
    val updateTag: String,
    val dlcTag: String,

    // ─── Game library ───────────────────────────────────────────────────────
    val play: String,
    val download: String,
    val downloadFifa: String,
    val playFifa: String,
    val getFifa: String,
    val dlcLibrary: String,
    val moreDlcComing: String,
    val moreDlcDesc: String,
    val trendingNow: String,
    val viewAll: String,
    val enterLibrary: String,
    val available: String,
    val season2016: String,

    // ─── Community ──────────────────────────────────────────────────────────
    val searchUsers: String,
    val searchUsersPlaceholder: String,
    val createPost: String,
    val newPost: String,
    val reply: String,
    val send: String,
    val typeMessage: String,
    val writeReply: String,
    val online: String,
    val lastSeen: String,
    val offline: String,
    val active: String,
    val away: String,

    // ─── Settings ───────────────────────────────────────────────────────────
    val settings: String,
    val accountSecurity: String,
    val changePassword: String,
    val changeEmail: String,
    val changeProfile: String,
    val pinLauncher: String,
    val language: String,
    val selectLanguage: String,
    val autoDetect: String,
    val logout: String,
    val saveProfile: String,

    // ─── Misc ───────────────────────────────────────────────────────────────
    val loading: String,
    val error: String,
    val retry: String,
    val cancel: String,
    val close: String,
    val refresh: String,
    val rate: String,
    val rated: String,

    // ─── Setup states (HomeScreen) ──────────────────────────────────────────
    val installFifa: String,
    val gameNotFound: String,
    val downloadOnce: String,
    val gameInstalled: String,
    val oneMoreStep: String,
    val dataNotReady: String,
    val openFifaData: String,
    val playFifa16: String,
    val blockedMaintenance: String,
    val processing: String,
    val downloading: String,

    // ─── Game detail ────────────────────────────────────────────────────────
    val aboutGame: String,
    val keyFeatures: String,
    val trustedByDlavie: String,
    val category: String,
    val version: String,
    val size: String,
    val sports: String,
    val gameplayRealistic: String,
    val communityActive: String,
    val regularUpdates: String,
    val safeVerified: String,

    // ─── Community tabs ─────────────────────────────────────────────────────
    val allPosts: String,
    val following: String,
    val officialPosts: String,
    val members: String,
    val staff: String,
    val banned: String,
    val allUsers: String,

    // ─── Profile ────────────────────────────────────────────────────────────
    val myPosts: String,
    val savedPosts: String,
    val badges: String,
    val followers: String,
    val followingCount: String,
    val posts: String,
    val editProfile: String,
    val bio: String,

    // ─── Sort/filter ────────────────────────────────────────────────────────
    val newest: String,
    val oldest: String,
    val usernameAZ: String,
    val recentlyActive: String,
    val onlineFirst: String,

    // ─── DLC ────────────────────────────────────────────────────────────────
    val explore: String,
    val fifa16Season2016: String,
    val modFootball: String,
    val dlavieEdition: String,

    // ─── Live chat ──────────────────────────────────────────────────────────
    val liveChat: String,
    val connecting: String,
    val waitingDeveloper: String,
    val sessionClosedAuto: String,
    val cancelChat: String,
    val androidVersion: String,
    val start: String,

    // ─── Notification ───────────────────────────────────────────────────────
    val allNotifications: String,
    val unreadNotifications: String,
)

object Strings {

    /** Get strings for a language code. Falls back to English. */
    fun get(langCode: String): DLavieStrings {
        return when (langCode) {
            "id" -> ID
            "ms" -> MS
            "pt" -> PT
            "es" -> ES
            "de" -> DE
            "fr" -> FR
            "ja" -> JA
            "zh" -> ZH
            "ar" -> AR
            else -> EN  // English fallback
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    // ENGLISH (default)
    // ═══════════════════════════════════════════════════════════════════════
    val EN = DLavieStrings(
        home = "Home",
        discover = "Discover",
        dlc = "DLC",
        gameHub = "Games",
        community = "Community",
        profile = "Profile",
        update = "Update",
        search = "Search",
        searchPlaceholder = "Search games, community, updates…",
        notifications = "Notifications",
        menu = "Menu",
        loginTitle = "FIFA 16 Mobile Mod Hub",
        loginSubtitle = "Sign in to continue",
        loginWithGoogle = "Continue with Google",
        loginWithEmail = "Sign in with DLavie Account",
        registerAccount = "Create DLavie Account",
        continueAsGuest = "Continue as Guest",
        guestNotice = "Guest mode: browse only. To post, comment, download APK, and rate games, you need a DLavie account.",
        login = "Sign In",
        register = "Sign Up",
        email = "Email",
        password = "Password",
        confirmPassword = "Confirm Password",
        username = "Username",
        displayName = "Display Name",
        country = "Country",
        forgotPassword = "Forgot password?",
        back = "← Back",
        legalNotice = "By continuing, you agree to DLavie's Terms of Service and Privacy Policy.",
        completeProfile = "Complete Profile",
        completeProfileDesc = "Username is required for posting and commenting in the community.",
        saveAndContinue = "Save & Continue",
        loginRequired = "Login Required",
        later = "Maybe Later",
        loginNow = "Login Now",
        officialTag = "OFFICIAL",
        communityTag = "COMMUNITY",
        updateTag = "UPDATE",
        dlcTag = "DLC",
        play = "Play",
        download = "Download",
        downloadFifa = "Download FIFA 16 Now",
        playFifa = "Play FIFA 16",
        getFifa = "Get",
        dlcLibrary = "DLC Library",
        moreDlcComing = "More DLC coming soon",
        moreDlcDesc = "World Cup 2026, Euro 2024, and other editions will be available here.",
        trendingNow = "Trending Now",
        viewAll = "View all",
        enterLibrary = "Enter Library",
        available = "AVAILABLE",
        season2016 = "SEASON 2016",
        searchUsers = "Users",
        searchUsersPlaceholder = "Search community username…",
        createPost = "Create post",
        newPost = "New Post",
        reply = "Reply",
        send = "Send",
        typeMessage = "Type a message…",
        writeReply = "Write a reply…",
        online = "Online",
        lastSeen = "Last seen",
        offline = "Offline",
        active = "Active",
        away = "Away",
        settings = "Settings",
        accountSecurity = "Account & Security",
        changePassword = "Change Password",
        changeEmail = "Change Email",
        changeProfile = "Edit Profile",
        pinLauncher = "PIN Lock",
        language = "Language",
        selectLanguage = "Select Language",
        autoDetect = "Auto-detect",
        logout = "Logout",
        saveProfile = "Save Profile",
        loading = "Loading…",
        error = "Error",
        retry = "Retry",
        cancel = "Cancel",
        close = "Close",
        refresh = "Refresh",
        rate = "Rate",
        rated = "Rated",
        // Setup states
        installFifa = "Install FIFA 16",
        gameNotFound = "Game not found on this device.",
        downloadOnce = "Download and install the FIFA 16 APK file first. This is only done once.",
        gameInstalled = "Game Installed!",
        oneMoreStep = "One more step to start playing.",
        dataNotReady = "Game data not available. Open FIFA 16 — the game will automatically download OBB and data on first launch.",
        openFifaData = "Open FIFA 16 & Setup Data",
        playFifa16 = "Play FIFA 16",
        blockedMaintenance = "Blocked by Maintenance",
        processing = "Processing...",
        downloading = "Downloading...",
        // Game detail
        aboutGame = "About Game",
        keyFeatures = "Key Features",
        trustedByDlavie = "Trusted by DLavie",
        category = "Category",
        version = "Version",
        size = "Size",
        sports = "Sports",
        gameplayRealistic = "Realistic Gameplay",
        communityActive = "Active Community",
        regularUpdates = "Regular Updates",
        safeVerified = "Safe & Verified",
        // Community tabs
        allPosts = "All",
        following = "Following",
        officialPosts = "Official",
        members = "Members",
        staff = "Staff",
        banned = "Banned",
        allUsers = "All Users",
        // Profile
        myPosts = "My Posts",
        savedPosts = "Saved",
        badges = "Badges",
        followers = "Followers",
        followingCount = "Following",
        posts = "Posts",
        editProfile = "Edit Profile",
        bio = "Bio",
        // Sort/filter
        newest = "Newest",
        oldest = "Oldest",
        usernameAZ = "Username A-Z",
        recentlyActive = "Recently Active",
        onlineFirst = "Online First",
        // DLC
        explore = "Explore",
        fifa16Season2016 = "FIFA 16 Mobile — Season 2016",
        modFootball = "Mod Football · DLavie 26 Edition",
        dlavieEdition = "DLavie 26 Edition",
        // Live chat
        liveChat = "Live Chat",
        connecting = "Connecting...",
        waitingDeveloper = "Waiting for developer to accept your call.",
        sessionClosedAuto = "Session will auto-close in 5 min if no response.",
        cancelChat = "Cancel",
        androidVersion = "Android Version",
        start = "Start",
        // Notifications
        allNotifications = "All",
        unreadNotifications = "Unread",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // INDONESIAN
    // ═══════════════════════════════════════════════════════════════════════
    val ID = EN.copy(
        home = "Beranda",
        discover = "Jelajahi",
        community = "Komunitas",
        profile = "Profil",
        update = "Update",
        searchPlaceholder = "Cari game, komunitas, update…",
        loginSubtitle = "Masuk untuk lanjut",
        loginWithEmail = "Masuk dengan Akun DLavie",
        registerAccount = "Daftar Akun DLavie",
        continueAsGuest = "Lanjutkan sebagai Guest",
        guestNotice = "Guest mode: browse only. Untuk post, komentar, download APK, dan rate game, perlu akun DLavie.",
        login = "Masuk",
        register = "Daftar",
        forgotPassword = "Lupa password?",
        back = "← Kembali",
        legalNotice = "Dengan melanjutkan, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi DLavie.",
        completeProfile = "Lengkapi Profil",
        completeProfileDesc = "Username diperlukan untuk posting dan komentar di komunitas.",
        saveAndContinue = "Simpan & Lanjut",
        loginRequired = "Login Diperlukan",
        later = "Nanti Saja",
        loginNow = "Login Sekarang",
        communityTag = "KOMUNITAS",
        dlcLibrary = "DLC Library",
        moreDlcComing = "More DLC coming soon",
        moreDlcDesc = "World Cup 2026, Euro 2024, dan edisi lainnya akan tersedia di sini.",
        trendingNow = "Trending Sekarang",
        viewAll = "Lihat semua",
        enterLibrary = "Masuk Library",
        available = "TERSEDIA",
        searchUsersPlaceholder = "Cari username komunitas…",
        createPost = "Buat post",
        newPost = "Post Baru",
        writeReply = "Tulis balasan…",
        typeMessage = "Ketik pesan…",
        settings = "Pengaturan",
        accountSecurity = "Akun & Keamanan",
        changePassword = "Ganti Password",
        changeEmail = "Ganti Email",
        changeProfile = "Ganti Profil",
        pinLauncher = "PIN Launcher",
        language = "Bahasa",
        selectLanguage = "Pilih Bahasa",
        autoDetect = "Deteksi otomatis",
        logout = "Keluar",
        saveProfile = "Simpan Profil",
        // Setup states
        installFifa = "Instal FIFA 16",
        gameNotFound = "Game belum ditemukan di perangkat ini.",
        downloadOnce = "Unduh dan instal file APK FIFA 16 terlebih dahulu. Proses ini hanya dilakukan sekali.",
        gameInstalled = "Game Terinstall!",
        oneMoreStep = "Satu langkah lagi untuk mulai bermain.",
        dataNotReady = "Data game belum tersedia. Buka FIFA 16 — game akan otomatis mengunduh OBB dan data saat pertama kali dibuka.",
        openFifaData = "Buka FIFA 16 & Siapkan Data",
        playFifa16 = "Main FIFA 16",
        blockedMaintenance = "Diblokir Maintenance",
        processing = "Memproses...",
        downloading = "Mengunduh...",
        // Game detail
        aboutGame = "Tentang Game",
        keyFeatures = "Fitur Unggulan",
        trustedByDlavie = "Trusted by DLavie",
        category = "Kategori",
        version = "Versi",
        size = "Ukuran",
        sports = "Olahraga",
        gameplayRealistic = "Gameplay Realistis",
        communityActive = "Komunitas Aktif",
        regularUpdates = "Update Rutin",
        safeVerified = "Aman & Terverifikasi",
        // Community tabs
        allPosts = "Semua",
        following = "Mengikuti",
        officialPosts = "Official",
        members = "Member",
        staff = "Staff",
        banned = "Banned",
        allUsers = "Semua User",
        // Profile
        myPosts = "Post Saya",
        savedPosts = "Tersimpan",
        badges = "Lencana",
        followers = "Pengikut",
        followingCount = "Mengikuti",
        posts = "Post",
        editProfile = "Edit Profil",
        bio = "Bio",
        // Sort
        newest = "Terbaru",
        oldest = "Terlama",
        usernameAZ = "Username A-Z",
        recentlyActive = "Paling Aktif",
        onlineFirst = "Online duluan",
        // DLC
        explore = "Jelajahi",
        fifa16Season2016 = "FIFA 16 Mobile — Season 2016",
        modFootball = "Mod Football · DLavie 26 Edition",
        dlavieEdition = "DLavie 26 Edition",
        // Live chat
        liveChat = "Live Chat",
        connecting = "Menghubungkan...",
        waitingDeveloper = "Menunggu developer menerima panggilan Anda.",
        sessionClosedAuto = "Sesi akan ditutup otomatis dalam 5 menit jika tidak ada respon.",
        cancelChat = "Batalkan",
        androidVersion = "Versi Android",
        start = "Mulai",
        // Notifications
        allNotifications = "Semua",
        unreadNotifications = "Belum dibaca",
    )
    // ═══════════════════════════════════════════════════════════════════════
    val MS = EN.copy(
        home = "Laman Utama",
        discover = "Terokai",
        community = "Komuniti",
        profile = "Profil",
        update = "Kemas Kini",
        searchPlaceholder = "Cari permainan, komuniti, kemas kini…",
        loginSubtitle = "Log masuk untuk teruskan",
        loginWithEmail = "Log masuk dengan Akaun DLavie",
        registerAccount = "Daftar Akaun DLavie",
        continueAsGuest = "Teruskan sebagai Tetamu",
        guestNotice = "Mod tetamu: layari sahaja. Untuk pos, komen, muat turun APK, dan kadar permainan, anda perlukan akaun DLavie.",
        login = "Log Masuk",
        register = "Daftar",
        forgotPassword = "Lupa kata laluan?",
        back = "← Kembali",
        legalNotice = "Dengan meneruskan, anda bersetuju dengan Terma Perkhidmatan dan Dasar Privasi DLavie.",
        completeProfile = "Lengkapkan Profil",
        completeProfileDesc = "Username diperlukan untuk pos dan komen dalam komuniti.",
        saveAndContinue = "Simpan & Teruskan",
        loginRequired = "Log Masuk Diperlukan",
        later = "Kemudian",
        loginNow = "Log Masuk Sekarang",
        trendingNow = "Popular Sekarang",
        viewAll = "Lihat semua",
        enterLibrary = "Masuk Library",
        available = "TERSEDIA",
        searchUsersPlaceholder = "Cari username komuniti…",
        createPost = "Buat pos",
        newPost = "Pos Baharu",
        writeReply = "Tulis balasan…",
        typeMessage = "Taip mesej…",
        settings = "Tetapan",
        accountSecurity = "Akaun & Keselamatan",
        changePassword = "Tukar Kata Laluan",
        changeEmail = "Tukar Email",
        changeProfile = "Edit Profil",
        pinLauncher = "PIN Launcher",
        language = "Bahasa",
        selectLanguage = "Pilih Bahasa",
        autoDetect = "Auto-kesan",
        logout = "Log Keluar",
        saveProfile = "Simpan Profil",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // PORTUGUESE
    // ═══════════════════════════════════════════════════════════════════════
    val PT = EN.copy(
        home = "Início",
        discover = "Descobrir",
        community = "Comunidade",
        profile = "Perfil",
        update = "Atualização",
        searchPlaceholder = "Pesquisar jogos, comunidade, atualizações…",
        loginSubtitle = "Entrar para continuar",
        loginWithEmail = "Entrar com Conta DLavie",
        registerAccount = "Criar Conta DLavie",
        continueAsGuest = "Continuar como Convidado",
        guestNotice = "Modo convidado: apenas navegação. Para postar, comentar, baixar APK e avaliar jogos, você precisa de uma conta DLavie.",
        login = "Entrar",
        register = "Cadastrar",
        forgotPassword = "Esqueceu a senha?",
        back = "← Voltar",
        legalNotice = "Ao continuar, você concorda com os Termos de Serviço e Política de Privacidade da DLavie.",
        completeProfile = "Completar Perfil",
        completeProfileDesc = "Nome de usuário é necessário para postar e comentar na comunidade.",
        saveAndContinue = "Salvar & Continuar",
        loginRequired = "Login Necessário",
        later = "Talvez Depois",
        loginNow = "Entrar Agora",
        trendingNow = "Em Alta Agora",
        viewAll = "Ver tudo",
        enterLibrary = "Entrar na Biblioteca",
        available = "DISPONÍVEL",
        searchUsersPlaceholder = "Pesquisar username da comunidade…",
        createPost = "Criar post",
        newPost = "Nova Postagem",
        writeReply = "Escrever resposta…",
        typeMessage = "Digite uma mensagem…",
        settings = "Configurações",
        accountSecurity = "Conta & Segurança",
        changePassword = "Alterar Senha",
        changeEmail = "Alterar Email",
        changeProfile = "Editar Perfil",
        pinLauncher = "Bloqueio PIN",
        language = "Idioma",
        selectLanguage = "Selecionar Idioma",
        autoDetect = "Detecção automática",
        logout = "Sair",
        saveProfile = "Salvar Perfil",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // SPANISH
    // ═══════════════════════════════════════════════════════════════════════
    val ES = EN.copy(
        home = "Inicio",
        discover = "Descubrir",
        community = "Comunidad",
        profile = "Perfil",
        update = "Actualización",
        searchPlaceholder = "Buscar juegos, comunidad, actualizaciones…",
        loginSubtitle = "Inicia sesión para continuar",
        loginWithEmail = "Iniciar sesión con Cuenta DLavie",
        registerAccount = "Crear Cuenta DLavie",
        continueAsGuest = "Continuar como Invitado",
        guestNotice = "Modo invitado: solo navegación. Para publicar, comentar, descargar APK y calificar juegos, necesitas una cuenta DLavie.",
        login = "Iniciar Sesión",
        register = "Registrarse",
        forgotPassword = "¿Olvidaste tu contraseña?",
        back = "← Volver",
        legalNotice = "Al continuar, aceptas los Términos de Servicio y la Política de Privacidad de DLavie.",
        completeProfile = "Completar Perfil",
        completeProfileDesc = "Se requiere nombre de usuario para publicar y comentar en la comunidad.",
        saveAndContinue = "Guardar & Continuar",
        loginRequired = "Inicio de Sesión Requerido",
        later = "Tal vez después",
        loginNow = "Iniciar Sesión Ahora",
        trendingNow = "Tendencias Ahora",
        viewAll = "Ver todo",
        enterLibrary = "Entrar a la Biblioteca",
        available = "DISPONIBLE",
        searchUsersPlaceholder = "Buscar username de comunidad…",
        createPost = "Crear publicación",
        newPost = "Nueva Publicación",
        writeReply = "Escribir respuesta…",
        typeMessage = "Escribe un mensaje…",
        settings = "Configuración",
        accountSecurity = "Cuenta & Seguridad",
        changePassword = "Cambiar Contraseña",
        changeEmail = "Cambiar Email",
        changeProfile = "Editar Perfil",
        pinLauncher = "Bloqueo PIN",
        language = "Idioma",
        selectLanguage = "Seleccionar Idioma",
        autoDetect = "Detección automática",
        logout = "Cerrar Sesión",
        saveProfile = "Guardar Perfil",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // GERMAN
    // ═══════════════════════════════════════════════════════════════════════
    val DE = EN.copy(
        home = "Startseite",
        discover = "Entdecken",
        community = "Community",
        profile = "Profil",
        update = "Update",
        searchPlaceholder = "Spiele, Community, Updates suchen…",
        loginSubtitle = "Anmelden um fortzufahren",
        loginWithEmail = "Mit DLavie Konto anmelden",
        registerAccount = "DLavie Konto erstellen",
        continueAsGuest = "Als Gast fortfahren",
        guestNotice = "Gastmodus: nur浏览. Zum Posten, Kommentieren, APK herunterladen und Bewerten benötigen Sie ein DLavie Konto.",
        login = "Anmelden",
        register = "Registrieren",
        forgotPassword = "Passwort vergessen?",
        back = "← Zurück",
        legalNotice = "Durch Fortfahren stimmen Sie den Nutzungsbedingungen und der Datenschutzrichtlinie von DLavie zu.",
        completeProfile = "Profil vervollständigen",
        completeProfileDesc = "Benutzername ist erforderlich für Community-Posts und Kommentare.",
        saveAndContinue = "Speichern & Weiter",
        loginRequired = "Anmeldung erforderlich",
        later = "Vielleicht später",
        loginNow = "Jetzt anmelden",
        trendingNow = "Jetzt im Trend",
        viewAll = "Alle anzeigen",
        enterLibrary = "Bibliothek öffnen",
        available = "VERFÜGBAR",
        searchUsersPlaceholder = "Community-Benutzername suchen…",
        createPost = "Beitrag erstellen",
        newPost = "Neuer Beitrag",
        writeReply = "Antwort schreiben…",
        typeMessage = "Nachricht eingeben…",
        settings = "Einstellungen",
        accountSecurity = "Konto & Sicherheit",
        changePassword = "Passwort ändern",
        changeEmail = "Email ändern",
        changeProfile = "Profil bearbeiten",
        pinLauncher = "PIN-Sperre",
        language = "Sprache",
        selectLanguage = "Sprache auswählen",
        autoDetect = "Automatische Erkennung",
        logout = "Abmelden",
        saveProfile = "Profil speichern",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // FRENCH
    // ═══════════════════════════════════════════════════════════════════════
    val FR = EN.copy(
        home = "Accueil",
        discover = "Découvrir",
        community = "Communauté",
        profile = "Profil",
        update = "Mise à jour",
        searchPlaceholder = "Rechercher jeux, communauté, mises à jour…",
        loginSubtitle = "Connectez-vous pour continuer",
        loginWithEmail = "Se connecter avec un compte DLavie",
        registerAccount = "Créer un compte DLavie",
        continueAsGuest = "Continuer en tant qu'invité",
        guestNotice = "Mode invité : navigation uniquement. Pour publier, commenter, télécharger l'APK et évaluer les jeux, vous avez besoin d'un compte DLavie.",
        login = "Se connecter",
        register = "S'inscrire",
        forgotPassword = "Mot de passe oublié ?",
        back = "← Retour",
        legalNotice = "En continuant, vous acceptez les Conditions d'utilisation et la Politique de confidentialité de DLavie.",
        completeProfile = "Compléter le profil",
        completeProfileDesc = "Le nom d'utilisateur est requis pour publier et commenter dans la communauté.",
        saveAndContinue = "Enregistrer & Continuer",
        loginRequired = "Connexion requise",
        later = "Peut-être plus tard",
        loginNow = "Se connecter maintenant",
        trendingNow = "Tendance maintenant",
        viewAll = "Voir tout",
        enterLibrary = "Entrer dans la bibliothèque",
        available = "DISPONIBLE",
        searchUsersPlaceholder = "Rechercher un nom d'utilisateur…",
        createPost = "Créer une publication",
        newPost = "Nouvelle publication",
        writeReply = "Écrire une réponse…",
        typeMessage = "Tapez un message…",
        settings = "Paramètres",
        accountSecurity = "Compte & Sécurité",
        changePassword = "Changer le mot de passe",
        changeEmail = "Changer l'email",
        changeProfile = "Modifier le profil",
        pinLauncher = "Verrouillage PIN",
        language = "Langue",
        selectLanguage = "Sélectionner la langue",
        autoDetect = "Détection automatique",
        logout = "Se déconnecter",
        saveProfile = "Enregistrer le profil",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // JAPANESE
    // ═══════════════════════════════════════════════════════════════════════
    val JA = EN.copy(
        home = "ホーム",
        discover = "発見",
        community = "コミュニティ",
        profile = "プロフィール",
        update = "アップデート",
        searchPlaceholder = "ゲーム、コミュニティ、アップデートを検索…",
        loginSubtitle = "続行するにはサインイン",
        loginWithEmail = "DLavieアカウントでサインイン",
        registerAccount = "DLavieアカウントを作成",
        continueAsGuest = "ゲストとして続行",
        guestNotice = "ゲストモード: 閲覧のみ。投稿、コメント、APKダウンロード、ゲーム評価にはDLavieアカウントが必要です。",
        login = "サインイン",
        register = "登録",
        forgotPassword = "パスワードをお忘れですか？",
        back = "← 戻る",
        legalNotice = "続行することで、DLavieの利用規約とプライバシーポリシーに同意します。",
        completeProfile = "プロフィール完了",
        completeProfileDesc = "コミュニティでの投稿とコメントにはユーザー名が必要です。",
        saveAndContinue = "保存して続行",
        loginRequired = "ログインが必要",
        later = "後で",
        loginNow = "今すぐログイン",
        trendingNow = "今トレンド",
        viewAll = "すべて表示",
        enterLibrary = "ライブラリに入る",
        available = "利用可能",
        searchUsersPlaceholder = "コミュニティのユーザー名を検索…",
        createPost = "投稿を作成",
        newPost = "新規投稿",
        writeReply = "返信を書く…",
        typeMessage = "メッセージを入力…",
        settings = "設定",
        accountSecurity = "アカウント & セキュリティ",
        changePassword = "パスワード変更",
        changeEmail = "メール変更",
        changeProfile = "プロフィール編集",
        pinLauncher = "PINロック",
        language = "言語",
        selectLanguage = "言語を選択",
        autoDetect = "自動検出",
        logout = "ログアウト",
        saveProfile = "プロフィール保存",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // CHINESE (Simplified)
    // ═══════════════════════════════════════════════════════════════════════
    val ZH = EN.copy(
        home = "首页",
        discover = "发现",
        community = "社区",
        profile = "个人资料",
        update = "更新",
        searchPlaceholder = "搜索游戏、社区、更新…",
        loginSubtitle = "登录以继续",
        loginWithEmail = "使用DLavie账户登录",
        registerAccount = "创建DLavie账户",
        continueAsGuest = "以访客身份继续",
        guestNotice = "访客模式：仅浏览。要发布、评论、下载APK和评价游戏，您需要DLavie账户。",
        login = "登录",
        register = "注册",
        forgotPassword = "忘记密码？",
        back = "← 返回",
        legalNotice = "继续即表示您同意DLavie的服务条款和隐私政策。",
        completeProfile = "完善资料",
        completeProfileDesc = "社区发帖和评论需要用户名。",
        saveAndContinue = "保存并继续",
        loginRequired = "需要登录",
        later = "稍后",
        loginNow = "立即登录",
        trendingNow = "现在热门",
        viewAll = "查看全部",
        enterLibrary = "进入库",
        available = "可用",
        searchUsersPlaceholder = "搜索社区用户名…",
        createPost = "创建帖子",
        newPost = "新帖",
        writeReply = "写回复…",
        typeMessage = "输入消息…",
        settings = "设置",
        accountSecurity = "账户与安全",
        changePassword = "修改密码",
        changeEmail = "修改邮箱",
        changeProfile = "编辑资料",
        pinLauncher = "PIN锁",
        language = "语言",
        selectLanguage = "选择语言",
        autoDetect = "自动检测",
        logout = "退出登录",
        saveProfile = "保存资料",
    )

    // ═══════════════════════════════════════════════════════════════════════
    // ARABIC (RTL — right-to-left)
    // ═══════════════════════════════════════════════════════════════════════
    val AR = EN.copy(
        home = "الرئيسية",
        discover = "اكتشف",
        community = "المجتمع",
        profile = "الملف الشخصي",
        update = "تحديث",
        searchPlaceholder = "البحث عن الألعاب والمجتمع والتحديثات…",
        loginSubtitle = "سجل الدخول للمتابعة",
        loginWithEmail = "تسجيل الدخول بحساب DLavie",
        registerAccount = "إنشاء حساب DLavie",
        continueAsGuest = "المتابعة كضيف",
        guestNotice = "وضع الضيف: التصفح فقط. للنشر والتعليق وتنزيل APK وتقييم الألعاب، تحتاج إلى حساب DLavie.",
        login = "تسجيل الدخول",
        register = "إنشاء حساب",
        forgotPassword = "نسيت كلمة المرور؟",
        back = "→ رجوع",
        legalNotice = "بالمتابعة، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بـ DLavie.",
        completeProfile = "إكمال الملف الشخصي",
        completeProfileDesc = "اسم المستخدم مطلوب للنشر والتعليق في المجتمع.",
        saveAndContinue = "حفظ ومتابعة",
        loginRequired = "تسجيل الدخول مطلوب",
        later = "ربما لاحقاً",
        loginNow = "تسجيل الدخول الآن",
        trendingNow = "الرائج الآن",
        viewAll = "عرض الكل",
        enterLibrary = "دخل المكتبة",
        available = "متاح",
        searchUsersPlaceholder = "البحث عن اسم مستخدم في المجتمع…",
        createPost = "إنشاء منشور",
        newPost = "منشور جديد",
        writeReply = "اكتب رداً…",
        typeMessage = "اكتب رسالة…",
        settings = "الإعدادات",
        accountSecurity = "الحساب والأمان",
        changePassword = "تغيير كلمة المرور",
        changeEmail = "تغيير البريد الإلكتروني",
        changeProfile = "تعديل الملف الشخصي",
        pinLauncher = "قفل PIN",
        language = "اللغة",
        selectLanguage = "اختر اللغة",
        autoDetect = "كشف تلقائي",
        logout = "تسجيل الخروج",
        saveProfile = "حفظ الملف الشخصي",
    )
}

/** CompositionLocal for accessing strings in Compose. */
val LocalStrings = staticCompositionLocalOf { Strings.EN }
